import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // see:
  // https://github.com/facebook/docusaurus/blob/main/website/sidebars.ts
  docs: [
    'intro',
    {
      type: 'category',
      label: 'UN',
      link: {
        type: 'doc',
        id: 'UN/un',
      },
      items: [
        'UN/veto_power',
        'UN/how_to_expel_rf_from_un'
      ],
    },
    {
      type: 'category',
      label: 'Holy Land',
      link: {
        type: 'doc',
        id: 'Holy-Land/holy_land',
      },
      items: [
        'Holy-Land/borders_and_territory',
      ],
    },
    {
      type: 'category',
      label: 'ECHR',
      link: {
        type: 'doc',
        id: 'ECHR/echr',
      },
      items: [
        // 'ECHR/our_cases',
      ],
    },
    {
      type: 'category',
      label: 'Software',
      link: {
        type: 'doc',
        id: 'software/software',
      },
      items: [
        'software/highlighter',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
